FROM google/dart-runtime

ENV PORT=8080

ARG ENVIRONMENT
ENV ENVIRONMENT=$ENVIRONMENT
ENV SENTRY_ENVIRONMENT=$ENVIRONMENT
RUN echo Environment: $ENVIRONMENT

ARG VERSION
ENV VERSION=$VERSION
ENV SENTRY_RELEASE=$VERSION
RUN echo Version: $VERSION
